# -*- mode: ruby -*-
# vi: set ft=ruby :

print "Vagrantfile load begin...\n"
Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/xenial64"

	# reset var: if true, all flags, files and content will be erased on vagrant boot
	reset = false;

	# config.ssh.username = "vagrant"
	# config.ssh.password = "vagrant"

	# configurations for windows access, *nix users can ignore it
	config.ssh.insert_key = false
	config.ssh.compression = false
	config.winssh.shell = "powershell"

	# setting up private ip
	config.vm.network :private_network, ip: "192.168.68.8" #private IP

	# forwarding common used ports
	config.vm.network "forwarded_port", guest: 80, host: 2281, auto_correct: true
	config.vm.network "forwarded_port", guest: 8000, host: 2282, auto_correct: true
	
	#forwarding JBOSS common used ports
	#config.vm.network "forwarded_port", guest: 9994, host: 19994 # JBOSS Admin Console
	#config.vm.network "forwarded_port", guest: 8084, host: 18084 # JBOSS Endpoints
	#config.vm.network "forwarded_port", guest: 10003, host: 10003 # JBOSS Maven Deploy
	#config.vm.network "forwarded_port", guest: 9443, host: 19443 # WSO2 Console admin/admin
	#config.vm.network "forwarded_port", guest: 8243, host: 18243 # WSO2 Endpoints
	#config.vm.network "forwarded_port", guest: 8280, host: 18280 # WSO2 Endpoints
	#config.vm.network "forwarded_port", guest: 1521, host: 11521 # Oracle XE

	# configure shared folders
	config.vm.synced_folder "shared/", "/vagrant/shared/"

	# getting script to be runned on machine 'up' command
	if reset == true
		config.vm.provision "shell", path: File.join(
			File.expand_path(File.dirname(__FILE__)),
			"shared/reset_script.sh"
			)
	else
		config.vm.provision "shell", path: File.join(
			File.expand_path(File.dirname(__FILE__)),
			"shared/start_script.sh"
			)
	end

	# Vagrantfile output
	print "
		Vagrant base box: " << config.vm.box << "\n
		Private Network IP Address: 192.168.68.8
		Forwarded Ports: {
			guest: 80, host: 2281, auto_correct: true
			guest: 8000, host: 2282, auto_correct: true
		}
		./shared host folder will be mounted as /vagrant/shared/ on guest
		reset flag is set to: " << reset << "\n"

	# end of vagrant file
	print "Vagrantfile loaded\n"
end
